"""mango/cli.py

The `mango` command-line tool — the single entry point for every kind of
scaffolding mango offers: a new project (`mango init`), a new module
(`mango new-module`), and a new project's Alembic setup
(`mango init-migrations`). Built on `argparse` so it gets real `--help`
text, a `--version` flag, and consistent argument validation for free,
instead of the hand-rolled `sys.argv[1:]` parsing an earlier version of
this file did (no help text, no usage on bad args, silent
`IndexError`s on a missing argument).

Classes: none — this file only wires up CLI commands.

Functions (5):
    - new_module: writes a starter `module.py` for a new module into the
      given directory.
    - init_project_command: thin CLI wrapper around
      `mango.project.init_project`.
    - init_migrations_command: thin CLI wrapper around
      `mango.migrations.init_migrations`.
    - build_parser: constructs the argparse parser + all subcommands.
    - main: CLI entry point — parses argv, dispatches to the right
      command, and turns expected failures (FileExistsError, ValueError)
      into a clean one-line error instead of a raw traceback.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from mango import __version__
from mango.migrations import init_migrations
from mango.project import init_project

_MODULE_TEMPLATE = '''"""{path}

Module declaration for "{name}" — generated by `mango new-module`.
Fill in models/repository/service/schemas/router as the module grows;
none are required until the module actually needs them. Note this
starter never imports fastapi or pydantic directly — mango.Router,
mango.Schema, etc. ARE those classes under mango's own names.
"""
import mango

router = mango.Router()  # add this module's endpoints here


@router.get("/{name}/ping")
async def ping() -> dict:
    """Starter endpoint — replace or remove once real endpoints exist."""
    return {{"module": "{name}", "status": "ok"}}


@mango.module
class {class_name}(mango.MangoModule):
    """TODO: one-line description of what this module owns."""

    name = "{name}"
    router = router
    depends_on = ()  # names of other modules this one imports from
'''  # starter file content for a freshly scaffolded module


def new_module(name: str, directory: str = ".") -> Path:
    """Write a starter module.py for `name` into `directory/<name>/module.py`."""
    class_name = "".join(part.capitalize() for part in name.split("_")) + "Module"  # e.g. "user_profile" -> "UserProfileModule"
    target_dir = Path(directory) / name  # the new module's own subdirectory
    target_dir.mkdir(parents=True, exist_ok=True)
    target_file = target_dir / "module.py"  # the single generated file
    if target_file.exists():
        raise FileExistsError(f"{target_file} already exists")

    content = _MODULE_TEMPLATE.format(
        path=f"{name}/module.py", name=name, class_name=class_name
    )  # rendered template with the module's name substituted in
    target_file.write_text(content, encoding="utf-8")
    return target_file


def init_project_command(name: str, directory: str = ".") -> Path:
    """CLI wrapper: scaffold a full project named `name` into `directory/name/`."""
    return init_project(name, directory)


def init_migrations_command(base_import: str, directory: str = ".") -> Path:
    """CLI wrapper: scaffold alembic.ini + migrations/ into `directory`,
    wired to the declarative Base at `base_import` ("module.path:Base")."""
    return init_migrations(directory, base_import=base_import)


def build_parser() -> argparse.ArgumentParser:
    """Construct the `mango` argparse parser and all its subcommands."""
    parser = argparse.ArgumentParser(
        prog="mango",
        description="Scaffolding for mango projects — a new project, a new module, or a new project's Alembic setup.",
    )  # the top-level parser
    parser.add_argument(
        "--version", action="version", version=f"mango {__version__}"
    )  # `mango --version` prints the installed mango version and exits

    subcommands = parser.add_subparsers(dest="command")  # dest="command" so main() can dispatch on it

    init_parser = subcommands.add_parser(
        "init", help="Scaffold a new project (pyproject.toml, app/main.py, app/registry.py, app/db.py, ...)."
    )
    init_parser.add_argument("name", help="The new project's name (also its directory name).")
    init_parser.add_argument(
        "directory", nargs="?", default=".", help="Where to create the project (default: current directory)."
    )

    new_module_parser = subcommands.add_parser(
        "new-module", help="Scaffold a starter module.py for a new module."
    )
    new_module_parser.add_argument("name", help="The new module's name (also its subdirectory name).")
    new_module_parser.add_argument(
        "directory",
        nargs="?",
        default=".",
        help="Where to create the module's directory, e.g. app/modules (default: current directory).",
    )

    init_migrations_parser = subcommands.add_parser(
        "init-migrations", help="Scaffold an async-aware alembic.ini + migrations/env.py."
    )
    init_migrations_parser.add_argument(
        "base_import", help='Your declarative Base, as "module.path:AttributeName" (e.g. "app.db:Base").'
    )
    init_migrations_parser.add_argument(
        "directory", nargs="?", default=".", help="Project root to scaffold into (default: current directory)."
    )

    return parser


def main() -> None:
    """CLI entry point: parse argv, dispatch to the matching command."""
    parser = build_parser()  # the full argparse parser, with all subcommands registered
    args = parser.parse_args()  # parsed CLI arguments; argparse itself handles --help/bad-args/exits

    if args.command is None:
        parser.print_help()
        raise SystemExit(1)

    try:
        if args.command == "init":
            path = init_project_command(args.name, args.directory)
            print(f"created {path}/")
        elif args.command == "new-module":
            path = new_module(args.name, args.directory)
            print(f"created {path}")
        elif args.command == "init-migrations":
            path = init_migrations_command(args.base_import, args.directory)
            print(f"created {path} and {Path(args.directory) / 'migrations'}/")
    except (FileExistsError, ValueError) as exc:
        # Expected, user-actionable failures (target already exists, malformed
        # base_import, ...) — a clean one-line message, not a Python traceback.
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
