"""mango/migrations.py

Scaffolds a working Alembic setup wired to a project's declarative Base,
instead of hand-writing `alembic.ini` + `env.py` (async engine boilerplate,
metadata wiring, offline/online mode branching — ~100 lines nobody enjoys
writing from scratch, and easy to get subtly wrong, e.g. forgetting async
support and get a cryptic error the first time `alembic upgrade` runs).
Real migration *authoring* is still Alembic's job (`alembic revision
--autogenerate`) — this only removes the one-time setup cost.

Classes: none.

Functions (1):
    - init_migrations: writes alembic.ini + migrations/env.py +
      migrations/script.py.mako + an empty migrations/versions/ into a
      target directory.
"""
from __future__ import annotations

from pathlib import Path

_ALEMBIC_INI = """\
[alembic]
script_location = migrations

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""  # standard Alembic config — script_location is the only project-specific line

_ENV_PY = '''"""migrations/env.py — generated by `mango init-migrations`.

Wires Alembic to {base_import}'s metadata and reads the DB connection
string from the {database_url_env} environment variable. Async-aware
(uses AsyncEngine + run_sync), matching mango.Database's own engine setup.
"""
import asyncio
import os
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

from {base_module} import {base_attr}
{models_import_line}
config = context.config
database_url = os.environ["{database_url_env}"]  # single source of truth for the connection string
config.set_main_option("sqlalchemy.url", database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = {base_attr}.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Run migrations against an already-open connection."""
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Open an async engine, then run migrations against a sync-wrapped connection."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {{}}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations against a live DB connection."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''  # env.py template — base_module/base_attr/database_url_env are filled in by init_migrations()

_SCRIPT_MAKO = '''"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''  # standard Alembic revision-file template, unmodified from Alembic's own default


def init_migrations(
    directory: str, *, base_import: str, database_url_env: str = "DATABASE_URL", models_import: str | None = None
) -> Path:
    """Scaffold `alembic.ini` + `migrations/` into `directory`.

    Args:
        directory: project root to scaffold into (alembic.ini goes here,
            migrations/ is created alongside it).
        base_import: `"module.path:AttributeName"` pointing at your
            declarative Base, e.g. `"app.db:Base"`. Its `.metadata` is
            what Alembic diffs against for `--autogenerate`.
        database_url_env: environment variable `env.py` reads the DB
            connection string from at migration-run time. Keep this in
            sync with whatever you pass to `mango.Database(...)` — they
            should be the same connection string, read the same way.
        models_import: dotted module path that, when imported, has the
            side effect of importing every one of the project's ORM
            model modules (typically the project's own `registry`
            module, since it already imports every module.py — see
            `mango/cli.py`'s `init_migrations_command`, which defaults
            this from `project.mango`'s `registry` field). Declaring a
            model class is what registers its table on `Base.metadata`
            — importing `base_import` alone does NOT import any model
            module, so without this, `--autogenerate` silently diffs
            against an EMPTY metadata and produces an empty migration.
            Omit only if `base_import` itself already guarantees every
            model is imported as a side effect.

    Returns:
        The path to the created `alembic.ini`.

    Raises:
        ValueError: if `base_import` isn't in `"module:attr"` form.
        FileExistsError: if `alembic.ini` already exists in `directory`.
    """
    if ":" not in base_import:
        raise ValueError(f"base_import must be 'module.path:AttributeName', got {base_import!r}")
    base_module, base_attr = base_import.split(":", 1)  # split into the importable module path and the Base's attribute name

    root = Path(directory)  # the project root being scaffolded into
    ini_path = root / "alembic.ini"  # Alembic's own config file
    if ini_path.exists():
        raise FileExistsError(f"{ini_path} already exists")

    migrations_dir = root / "migrations"  # where env.py/script template/versions live
    versions_dir = migrations_dir / "versions"  # individual revision files go here
    versions_dir.mkdir(parents=True, exist_ok=True)

    models_import_line = (
        f"import {models_import}  # noqa: F401  (imports every model so Base.metadata is populated before autogenerate reads it)\n"
        if models_import
        else ""
    )

    ini_path.write_text(_ALEMBIC_INI, encoding="utf-8")
    (migrations_dir / "env.py").write_text(
        _ENV_PY.format(
            base_import=base_import,
            base_module=base_module,
            base_attr=base_attr,
            database_url_env=database_url_env,
            models_import_line=models_import_line,
        ),
        encoding="utf-8",
    )
    (migrations_dir / "script.py.mako").write_text(_SCRIPT_MAKO, encoding="utf-8")
    (versions_dir / ".gitkeep").write_text("", encoding="utf-8")  # keep the empty dir tracked in git

    return ini_path
